
name: Python package

# on:
#  schedule:
#  - cron: '0 */12 * * *'
env:
  DEEPL_KEY: ${{secrets.DEEPL_KEY}}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest deepl
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Translate
      run: |
        python translate.py
    - name: push
      run: |
        git config --global user.name "snitch0"
        git config --global user.email "snitch0@excel2rlang.com"
        git add .
        git commit -m "update"
        git push

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write